spring:
  profiles:
    active: local


--- #local ??R
spring:
  profiles: local
  data:
    mongodb:
#      uri: mongodb+srv://admin:1q2w3e4r!@cluster0.kjzqz.mongodb.net/SBlog?retryWrites=true&w=majority
        uri: mongodb://139.177.200.169:27117/Student


logging: # ROOT?? ?? ?? ?? ??
  level:
    root: info
